# Paths here are relative to container binding

# PLINK1.9 file prefix with path
  # must be a single file, but file can contain one or multiple chromosomes
plink_prefix: "/input_data/CG10k_NHW_hg19_Oct2017_filt"
out_dir: "/output_data"  # top-level directory for all output in container
code_dir: "/repo"  # top-level of topmed_imputation repo in container
chr: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]  # list of chromosome numbers with format [1,10,22]
orig_build: "hg19"  #  either "hg19" or "hg38"
to_build: "hg38"  # either "hg19" or "hg38"
imp:  "topmed"  # should be 'topmed', 'mich_hla_v1', 'mich_hla_v2', 'mich_1kg_p3_v5',  'mich_hrc_r1.1'
imp_rsq_filt: "0"  # should be 0, 0.001, 0.1, 0.2, 0.3
imp_name: "copdgene"  # job name for imputation server
zip_pw: "NxoyJ0BEVEU6yr"  # add from email when imputed job finishes
opt: "gt"  # option for "gt" only or "all" dosage information (much slower)
